# Generated by Django 4.2.22 on 2025-12-17 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210509_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='score',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
