# Generated by Django 4.2.22 on 2025-12-18 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_scan_score'),
    ]

    operations = [
    ]
